/**
 * IFJ projekt 2023
 * Varianta TRP - Hash table
 * @author Petr Plíhal, xpliha02
*/

#ifndef MAIN_H
#define MAIN_H


// Návratové hodnoty
#define COMPILATION_SUCCESSFUL 0
#define ERROR_LEXICAL_ANALYSIS 1
#define ERROR_SYNTACTIC_ANALYSIS 2
#define ERROR_SEMANTIC_DEFINING 3
#define ERROR_SEMANTIC_FUNCTION 4
#define ERROR_SEMANTIC_VARIABLE 5
#define ERROR_SEMANTIC_NO_RETURN 6
#define ERROR_SEMANTIC_TYPE_UNCOMPATIBLE 7
#define ERROR_SEMANTIC_TYPE_UNKNOWN 8
#define ERROR_SEMANTIC_OTHER 9
#define ERROR_INTERNAL 99

#endif